New Gui
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #13
Opened 2017-10-14 18:24 UTC by Ben-Graham

2017-11-15 01:13 UTC, bill-luu commented
![image](https://user-images.githubusercontent.com/15304203/32813217-320fd7dc-c966-11e7-8039-9079b2da7ffc.png)

Need to: 

- Update the font/size

- Add reactions to button presses (I'll get Mackey to send new icons for that)

- Set default text to blank or something else

- The volume control slider looks funky, is that the default or custom? 

- The Ui looks good, but we should really have a layout in it.

Let's get this updated, then I'll pass this along to Lisa for more review

2017-11-15 01:14 UTC, bill-luu commented
Also, we have some merge conflicts

2018-01-13 18:51 UTC, Ben-Graham commented
Opening a song by pressing the play button will change the icon but not start playing until it is pressed again. In this case the play icon will be the opposite of what it should be. Should add a check that a song is loaded before changing the icon make a song start playing automatically when it is loaded.

2018-01-13 19:00 UTC, Ben-Graham commented
Should remove the open button. We will change the functionality of that later so it opens a list of songs. Lets make it so songs load and begin playing when the play button is pressed. You could probably do that in another branch.

2018-01-13 21:04 UTC, Ben-Graham commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +void SongPlayer::progressChanged()
This doesn't need to be a function. We can move the emit into the positionChanged.

2018-01-13 21:04 UTC, Ben-Graham commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
> +    ui_.OpenButton().hide();     //Button is not displayed
Lets just delete the button for now instead of hiding it.

2018-01-13 21:04 UTC, Ben-Graham commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
>  void SongPlayerView::handleOpenButtonClicked()
If we're deleting the open button, we should also delete this function for now

2018-01-15 16:49 UTC, bill-luu commented
Travis Build is still failing.

2018-01-20 17:50 UTC, Ben-Graham commented on ViewLayer/SongPlayerView/SongPlayerView.h
>      SongPlayer& songPlayer_;
The compiler warns that these are in the wrong order. They should be listed in the same order that they appear as arguments in the constructor.

2018-01-20 17:50 UTC, Ben-Graham commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
> +void SongPlayerView::updateGUI(const QString& title, const QString& artist, const QImage& cover)
We are not using a cover image right now, so currently the cover parameter isn't used. Lets remove it for now until we implement that feature.

2018-01-20 18:25 UTC, Ben-Graham commented
Need to change the colour of progress bar and volume slider to 5c91a1

2018-01-20 18:59 UTC, Ben-Graham commented
Looks good to merge @bill-luu

2018-01-20 19:24 UTC, bill-luu commented
Nice job! The buttons slightly shift down a bit, after pressing the play button the first time (when the song title appears). Find a way around that, then it'll be good to me!

2018-01-20 19:25 UTC, bill-luu commented
Ayy lmao fixed it before I even finished my comment

2018-01-20 19:27 UTC, bill-luu requested changes

2018-01-20 19:27 UTC, bill-luu commented on ViewLayer/ProgressBar/ProgressBar.cpp
> +    int startAngle = -90 * 16;
This looks like some kind of magic number, let's put this in a namespace.

2018-01-20 19:27 UTC, bill-luu commented on ViewLayer/ProgressBar/ProgressBar.cpp
> +    int spanAngle = progress * 360 * 16;
As above, `360 * 16` is a bit out of nowhere, what do these values mean?

2018-01-20 19:47 UTC, bill-luu commented on ViewLayer/ProgressBar/ProgressBar.cpp
> +    const int DEGREES_IN_CIRCLE_TIMES_SIXTEEN = 5760; //16 * 360 1/16th degrees in a circle
Name it FULL_CIRCLE, then have a comment beforehand. 
````
// Angle must specified be in 1/16th of a degree
const int FULL_CIRCLE = 5760; // 360 * 16
````

2018-01-24 00:35 UTC, bill-luu approved these changes

2018-01-24 00:35 UTC, merged