Magnus/gui
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #23
Opened 2018-01-27 18:45 UTC by mglyngberg

Added shuffle and loop buttons.

2018-01-27 20:03 UTC, Ben-Graham requested changes

2018-01-27 20:03 UTC, Ben-Graham commented on BusinessLayer/SongControl/SongControl.cpp
> +    currentSongIndex_ = (rand() % files_.size());
might want to add a check that the number generated is not the number currently playing. During a quick test of the program I had the same song play 3 times in a row in a test library of about 35 songs.

2018-01-27 20:03 UTC, Ben-Graham commented on BusinessLayer/SongControl/SongControl.cpp
> +    if (playOrder_[playOrderIndex_] == -1)
As mentioned in person, lets have it so shuffling and going to a previous song lets plays another random song so we can keep reliable behaviour when not shuffling

2018-02-03 17:31 UTC, Ben-Graham approved these changes

2018-02-03 17:51 UTC, Ben-Graham commented
Need to fix shuffle play with only one song

2018-02-03 17:53 UTC, Ben-Graham requested changes

2018-02-03 17:53 UTC, Ben-Graham commented on BusinessLayer/SongControl/SongControl.cpp
> +    currentSongIndex_ = (rand() % files_.size());
check for case where there is only one song in the library

2018-02-15 00:00 UTC, bill-luu requested changes
I know you didn't do it, but I'd also rename the `SongPlayer::playFile()` function, since it just sets the media.

2018-02-15 00:00 UTC, bill-luu commented on BusinessLayer/SongControl/SongControl.cpp
> +    while(currentSongIndex_ == index)
Use a do while loop instead, so that the calculation is done first before checking the condition!

2018-02-17 18:45 UTC, bill-luu approved these changes

2018-02-17 18:54 UTC, Ben-Graham requested changes

2018-02-17 18:54 UTC, Ben-Graham commented on BusinessLayer/SongControl/SongControl.cpp
> +    srand(shuffleSeed_);
We can just use srand(time(0)) to create random numbers. It will be simpler.

2018-02-17 19:22 UTC, Ben-Graham approved these changes

2018-02-17 19:22 UTC, merged