Ben/new gui
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #27
Opened 2018-03-03 23:23 UTC by Ben-Graham

2018-03-10 18:43 UTC, bill-luu requested changes

2018-03-10 18:43 UTC, bill-luu commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +    album_.replace(" ", ""); //remove all spaces in album name for easier access to file path of album
Add in some extra whitespace to separate ideas

2018-03-10 18:43 UTC, bill-luu commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +    album_ = mediaPlayer_.metaData(QMediaMetaData::AlbumTitle).toString(); //retrieves the album name from current song
Don't need this comment

2018-03-10 18:43 UTC, bill-luu commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +    album_.replace(" ", ""); //remove all spaces in album name for easier access to file path of album
Add the comment above this line

2018-03-10 18:43 UTC, bill-luu commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +        while(color.lightness() < 40)
`40` & `10` are pretty arbitrary magic numbers, so add them to a namespace

2018-03-10 18:43 UTC, bill-luu commented on ViewLayer/ProgressBar/ProgressBar.cpp
> +    color_ = QColor(92,145,161,255);
Let's have the default color `QColor(92,145,161,255)` in the namespace

2018-03-10 18:43 UTC, bill-luu commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
>  #include <QDebug>
Remove `<QDebug>` from release code

2018-03-10 18:43 UTC, bill-luu commented on ViewLayer/SongPlayerUI/SongPlayerUi.h
> +    QPushButton& shuffle();
`shuffle` should be renamed to `shuffleButton`. Same with `loop`

2018-03-10 18:43 UTC, bill-luu commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
> +    QString styleSheet = "QSlider::groove:vertical {"
This stylesheet can go in the namespace

2018-03-10 18:43 UTC, bill-luu commented on BusinessLayer/SongPlayer/SongPlayer.cpp
> +    if(height != 0 && width != 0)
Add a comment to explain exactly when this isn't true.

2018-03-10 18:43 UTC, bill-luu commented on DataLayer/SongLibrary/Albumcheck.sh
> +song=(1-06+Animal 1-11+Armageddon+It 1-14+Hysteria 01-Take-On-Me)
I think we agreed to delete this

2018-03-10 23:18 UTC, bill-luu commented
Right now, if the song has no cover the volume slider's color bar turns black:
![image](https://user-images.githubusercontent.com/15304203/37247811-a628c494-247e-11e8-8d7d-a0510c9cc281.png)

2018-03-12 06:50 UTC, enochtsang commented
Nice icons!

2018-03-18 05:18 UTC, bill-luu requested changes
One more thing, and then I'll merge this.

2018-03-18 05:18 UTC, bill-luu commented on ViewLayer/SongPlayerView/SongPlayerView.cpp
> +    const QColor DEFAULT_COLOR = QColor(255,255,255,255);
Match this color with the default color of the other icons

2018-03-31 23:26 UTC, bill-luu approved these changes

2018-03-31 23:27 UTC, merged