moved code files and .pri and .pro files to src folder
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #29
Opened 2018-04-29 19:54 UTC by chordatgh1234

2018-04-29 23:47 UTC, bill-luu commented
Travis build is failing

2018-04-29 23:48 UTC, bill-luu commented
The travis.yml file needs to be updated with the change

2018-05-01 02:33 UTC, Ben-Graham requested changes

2018-05-01 02:33 UTC, Ben-Graham commented on .gitignore
> -*.png
Some album covers get saved as .png files. It would be best to keep this.

2018-05-26 03:44 UTC, Ben-Graham approved these changes

2018-05-26 05:37 UTC, merged