Magnus/libmpg123 song player
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #32
Opened 2018-06-21 01:03 UTC by mglyngberg

2018-06-23 19:52 UTC, Ben-Graham submitted a review, later dismissed
Change SongPlayer::getColor to implement multi threading like on the https://github.com/UCSolarCarTeam/Epsilon-Onboard-Media-Control/tree/Ben/MultiThreadColorChange branch. It uses the QConcurrent library.

2018-06-27 01:59 UTC, bill-luu requested changes

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/DeltaSongPlayer.cpp
> +#include "DeltaSongPlayer.h"
Lets rename this guy!

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/DeltaSongPlayer.cpp
> +    // most important thing used in thread later
This comment isn't really that helpful lol, let's explain what this does.

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/DeltaSongPlayer.cpp
> +        double times;
Let's expand this name to `timeSecs`, similar for minutes.

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/DeltaSongPlayer.cpp
> +        double times;
As above.

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/DeltaSongPlayer.h
> +#ifndef DeltaSongPlayer_H
Update to pragma

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/LibMpgMediaPlayer.cpp
> +#include <unistd.h>
We might be able to remove a few of these unused includes

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/LibMpgMediaPlayer.cpp
> +        return "Ben is Fat";
lol I can't believe Ben didn't see this

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/LibMpgMediaPlayer.h
> +#include "DeltaSongPlayer.h"
Again, there might be a few unused includes here

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/SongPlayer/SongPlayer.cpp
> +//    }
Remove these comments

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/SongPlayer/SongPlayer.cpp
> +//    qDebug() << "position: " << position;
Drop this comment

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/SongPlayer/SongPlayer.h
> +#include <unistd.h>
Miight not need these?

2018-06-27 01:59 UTC, bill-luu commented on src/BusinessLayer/threadclass.h
> +#define I_THREADCLASS_H
Switch to pragma

2018-07-13 06:17 UTC, bill-luu requested changes
Looking good! Last few comments.

2018-07-13 06:17 UTC, bill-luu commented on src/BusinessLayer/LibMpgMediaPlayer.cpp
> +        return "Ben is Fat";
Lets be nice :) 
`return QString()`

2018-07-13 06:17 UTC, bill-luu commented on src/BusinessLayer/SongPlayer/SongPlayer.cpp
> +QColor SongPlayer::getColor(QImage img, int thread_ID)
Keep strict camelCasing for argument names. `threadId`

2018-07-14 17:20 UTC, bill-luu approved these changes

2018-07-19 00:59 UTC, bill-luu approved these changes

2018-07-19 01:00 UTC, merged