SFT-81 Update song downloader.
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #47
Opened 2020-05-16 17:00 UTC by DatLam25

1. Unnecessary codes are removed from the original script. 
2. Create new script that automatically download all the songs from the AWS bucket down to local.
3. Update README with instructions on how to download the songs.

2020-05-16 17:57 UTC, bill-luu requested changes

2020-05-16 17:57 UTC, bill-luu commented on README.md
> +2. Obtaining Acess Keys
Misspelled `Access`

2020-05-16 17:57 UTC, bill-luu commented on README.md
> +To directly download from the aws bucket, you will need to obtain the access key ID and the secret acess key.
`secret access key`

2020-05-16 17:57 UTC, bill-luu commented on README.md
> +With the access keys, you can now run `./DownloadAllSong.sh` and inputting the acess keys into the apporiate places. The region name is `us-west-2`.
`acess` :)

2020-05-16 17:57 UTC, bill-luu commented on README.md
> +With the access keys, you can now run `./DownloadAllSong.sh` and inputting the acess keys into the apporiate places. The region name is `us-west-2`.
`appropriate`

2020-05-16 17:57 UTC, bill-luu commented
Is there any point to the original script if the new one works?

2020-05-16 17:59 UTC, mglyngberg commented
> 
> 
> Is there any point to the original script if the new one works?

I can see value if someone only wants to test the music player with a couple of songs instead of having to download all of them. It might be better to add a flag or something to the new script instead of having two though.

2020-05-16 21:09 UTC, bill-luu requested changes

2020-05-16 21:09 UTC, bill-luu commented on DownloadSongs.sh
> +	aws configure
We don't need to configure every time we run the script, it makes more sense to me that this step should be done manually, described in the readme in step 2.

2020-05-16 21:09 UTC, bill-luu commented on DownloadSongs.sh
> +done
If we run the script with `-a`, there's no point in downloading these songs again

2020-05-17 18:33 UTC, bill-luu requested changes

2020-05-17 18:33 UTC, bill-luu commented on README.md
> +Run `aws configure` in the terminal to configure the profile for AWS. Input the access keys obtained. The region name is `us-west-2`.
Seperate sentences so it's one line each, it's easier to read and still shows up in the rich text view as one paragraph.
```
Run `aws configure` in the terminal to configure the profile for AWS.
Input the access keys obtained.
The region name is `us-west-2`.
```

2020-05-17 18:33 UTC, bill-luu commented on README.md
> +If you only need a small number of song, you can run the `./DownloadSongs.sh` in the terminal to download a pre-selected selection of songs.
`a small number of song`->`a small number of songs`

2020-05-22 00:14 UTC, bill-luu approved these changes

2020-05-22 00:22 UTC, merged