Working build of song player
UCSolarCarTeam/Epsilon-Onboard-Media-Control pull request #6
Opened 2016-11-09 21:18 UTC by Ben-Graham

Also continues #2

2016-11-10 20:09 UTC, bill-luu commented on song_player/Makefile
> +#############################################################################
This file can also be in the `.gitignore`

2016-11-10 20:09 UTC, bill-luu commented on OnBoard-Media-Control/i_threadable.h
> +#define I_THREADABLE_H
Remove the `#ifndef`s, let's stick with `#pragma once`.

2016-11-10 20:09 UTC, bill-luu commented on song_loader/song_loader.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
I think this entire file can be in the `.gitignore`

2016-11-10 20:09 UTC, bill-luu commented on song_player/moc_songplayer.cpp
> +/****************************************************************************
All of the `moc_` files can go in the `.gitignore` too

2016-11-10 20:09 UTC, bill-luu commented on song_player/song_player.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
As above, add to the `.gitignore`

2016-11-12 16:25 UTC, bill-luu commented on song_player/moc_songplayer.cpp
> +/****************************************************************************
Disregard this, take a look at my comment later on.

2016-11-12 16:25 UTC, bill-luu commented on song_player/Makefile
> +#############################################################################
Disregard this comment, take a look at my later one.

2016-11-12 17:08 UTC, bill-luu requested changes

2016-11-12 17:08 UTC, bill-luu commented on OnBoard-Media-Control/i_threadable.h
> +
Watch the whitespacing

2016-11-12 17:08 UTC, bill-luu commented on OnBoard-Media-Control/i_threadable.h
> +#ifndef I_THREADABLE_H
Where does this file fit into the new plan?

2016-11-12 17:08 UTC, bill-luu requested changes

2016-11-12 17:08 UTC, bill-luu commented on song_player/ui_songplayer.h
> +/********************************************************************************
This can also be in the `.gitignore`

2016-11-27 05:48 UTC, bill-luu requested changes
I didn't review anything in `song_loader` since we aren't using it in the new plan.

Good job getting this thing to play songs! That's awesome :)

A big part of `songplayer` seems to be UI stuff, so it sounds like a lot of it will be changed as we get started on the front end. I think that can be saved until we get there.

Your file name and the class should have the same name, so either change `songplayer` to `MusicPlayer` or vice versa. Also keep your file names in `CapCase`. 

Don't forget to run this through astyle before merging.

2016-11-27 05:48 UTC, bill-luu commented on OnBoard-Media-Control/main.cpp
> +#include "../song_player/songplayer.h"
Because it's in the `OnBoardMediaControl.pro`, there's no need to include relative paths in the include. `"song_player/songplayer.h" is sufficient.

2016-11-27 05:48 UTC, bill-luu commented on .gitignore
> +#Makefile
I don't think you need any of these comments.

2016-11-27 05:48 UTC, bill-luu commented on .gitignore
> +i_threadable.h
Not sure why you put this here, but if it won't be used in the plan, you can just get rid of the file.

2016-11-27 05:48 UTC, bill-luu commented on song_loader/song_loader.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
Commit this out.

2016-11-27 05:48 UTC, bill-luu commented on song_player/ui_songplayer.h
> +/********************************************************************************
Commit this out

2016-11-27 05:48 UTC, bill-luu commented on song_loader/songplayer.h
> +#pragma once
Is this another `songplayer.h`? It's different from the one in `song_player`.

2016-11-27 05:48 UTC, bill-luu commented on song_player/songplayer.h
> +QT_FORWARD_DECLARE_CLASS(QSlider)
I've never seen `QT_FORWARD_DECLARE_CLASS()` used before and nothing on Google is helping out....can you, @enochtsang or @bseto chime in?

2016-11-28 17:12 UTC, enochtsang commented on song_player/songplayer.h
> +QT_FORWARD_DECLARE_CLASS(QSlider)
http://article.gmane.org/gmane.comp.lib.qt.general/13667 they should be replaced with normal namespaces.

2016-12-02 00:36 UTC, bill-luu requested changes
Once you have these changes, that'll be good to me. @enochtsang or @bseto can merge.

2016-12-02 00:36 UTC, bill-luu commented on .gitignore
> +
Only have 1 new line at the end of the file.

2016-12-02 00:36 UTC, bill-luu commented on song_player/songplayer.ui
> +<ui version="4.0">
Rename this file to `SongPlayer.ui`

2016-12-02 00:36 UTC, bill-luu commented on song_player/ui_songplayer.h
> +/********************************************************************************
I guess you have to commit this out first before adding it to the `.gitignore` :p

2016-12-15 03:44 UTC, bill-luu commented
There's still a couple of things that still need addressing. 
All the `songloader` stuff can just be removed, since we aren't using it.
Also, Travis is still failing.

2017-01-12 02:11 UTC, bill-luu requested changes

2017-01-12 02:11 UTC, bill-luu commented on OnBoard-Media-Control/main.cpp
> +    app.setOrganizationDomain("qt-project.org");
Either remove this or change it to www.calgarysolarcar.ca

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.cpp
> +void SongPlayer::createWidgets()
This can all stay for now, but when you start implementing the GUI, a lot of the work will be done within `SongPlayer.ui`. It's better to keep all the GUI code all in one place as much as we can, rather than have it all over the place.

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.cpp
> +    QTime duration(0, position / 60000, qRound((position % 60000) / 1000.0));
These constant magic numbers used for time conversions can go in a namespace at the beginning with a descriptive name such as `MS_TO_MINUTES` and `MS_TO_SECONDS`

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.cpp
> +    positionSlider->setPageStep(duration / 10);
`10` can also be put as a magic number named `PAGE_STEP_INCREMENTS`

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.cpp
> +    const QStringList musicPaths = QStandardPaths::standardLocations(QStandardPaths::MusicLocation);
This will direct the user to the default Music Folder of the OS, change this to the `SongLibrary` path.

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.cpp
> +    positionSlider->setPageStep(duration / 10);
Also, not something to think about right now, but currently, clicking on the slider increments the position by a step. We'll have to change it so that clicking on the slider instantly jumps to that position.

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.h
> +    void createThumbnailToolBar();
The above 3 functions are not defined in the `.cpp` file. If we're not using them let's drop em.

2017-01-12 02:11 UTC, bill-luu commented on song_player/SongPlayer.h
> +#include <QWidget>
These includes should be in alphabetical order

2017-01-12 02:11 UTC, bill-luu commented on OnBoard-Media-Control/main.cpp
> +    settings.beginGroup("shell");
I get the purpose of the `SupportedTypes` group, but what's this one for?

2017-01-12 02:27 UTC, bill-luu commented on .travis.yml
> +    - cd ..
Right now, Travis is unable to find `astylerc`. I think that's because you moved out of the directory, so delete this and it should be good.

2017-01-12 02:29 UTC, Ben-Graham commented on song_player/SongPlayer.cpp
> +    const QStringList musicPaths = QStandardPaths::standardLocations(QStandardPaths::MusicLocation);
This is fixed in the song controller

2017-01-12 03:05 UTC, bill-luu requested changes

2017-01-12 03:05 UTC, bill-luu commented on .travis.yml
> -    - make
We still have to run `qmake` and `make` here to see if it builds properly.

2017-01-12 05:30 UTC, bill-luu approved these changes

2017-01-16 22:34 UTC, bill-luu commented on .travis.yml
> +    - "! (astyle "*.h" "*.cpp" -r --dry-run --options=astylerc | grep formatted)"
...I think I was wrong about this, drop the quotation marks you added in and it should work now!

2017-01-18 02:28 UTC, ExtraGravity requested changes
Remove the songs, if you want you can add the songs to S3 and create a script to download them via wget, but the repo gets too big with the binary files in there.

2017-01-18 02:28 UTC, ExtraGravity commented on OnBoard-Media-Control/main.cpp
> +    player.show();
Putting this much stuff in the main.cpp file and main function at all isn't as extensible. It's better to just create a separate object that IS the app. In this case you'd have a separate class called `OnboardMediaControl`, refer to this directory https://github.com/UCSolarCarTeam/Delta-Desktop-Client-Telemetry/tree/master/SchulichDeltaDesktopTelemetry

2017-01-18 02:28 UTC, ExtraGravity commented on Makefile
> +# Project:  OnBoardMediaControl.pro
This file shouldn't be included, it should be added to the gitignore.

2017-01-18 02:28 UTC, ExtraGravity commented on song_player/SongPlayer.h
> +#include <QToolButton>
I don't think all these includes are necessary.

2017-01-18 02:28 UTC, ExtraGravity commented on song_player/SongPlayer.h
> +    QPoint offset;
Private members should have trailing underscores.

2017-01-18 02:28 UTC, ExtraGravity commented on song_player/SongPlayer.cpp
> +        QFileDialog::getOpenFileName(this, tr("open file"),
Pretty messy line here. Probably better to break it up to a few different lines.

2017-01-18 02:28 UTC, ExtraGravity commented on song_player/SongPlayer.cpp
> +    if (!filePath.isEmpty())
What if it is empty? I imagine there should at least be a warning or something somewhere.

2017-01-21 17:39 UTC, Ben-Graham commented on song_player/SongPlayer.cpp
> +        QFileDialog::getOpenFileName(this, tr("open file"),
This entire function is re written in the Song Controller branch and contains fewer lines

2017-01-24 21:45 UTC, ExtraGravity requested changes
Update the README. The UI and logic are all bundled into the song_player, please seperate them. Any class dealing with UI components, should only ever deal with UI components.

2017-01-24 21:45 UTC, enochtsang commented on OnBoard-Media-Control/main.cpp
> +    player.show();
None of this stuff should be here. All of it should be encapsulated in `OnBoardMediaControl`. Look at all the other projects and follow suit.

2017-01-24 21:45 UTC, enochtsang commented on OnBoardMediaControl.pro
> +song_player/SongPlayer.cpp\
Indent the stuff the goes together. Rename `song_player` to match conventions.

2017-01-24 21:45 UTC, enochtsang commented on OnBoardMediaControl.pro
> +FORMS    += song_player/SongPlayer.ui
This whole file is formatted pretty terribly, clean it up.

2017-01-24 21:45 UTC, enochtsang commented on SongDownloadScript.sh
> +cd SongLibrary
This folder doesn't exist in the repo. Create the folder with this script inside and remove this line. Also don't end scripts with "Script", the .sh tells us that already. Naming scripts based what they do. Like any other executable.

2017-01-24 21:45 UTC, enochtsang commented on song_player/SongPlayer.h
> +    void openFile();
This class does a shitload. The song logic and the UI needs to be separated into different classes.

2017-03-11 20:30 UTC, bill-luu commented
Closing this for now while restructuring is happening.

2017-03-11 20:30 UTC, closed without merging